SELECT SHP.STORE_ID COD_FARMA,
	    ST.NM_ORGN FARMACIA,
	    SHP.ORDER_ID,
	    SHP.ASN_ID,
	    SHP.INVOICE_ID FACTURA,
	    SHP.FROM_LOCATION_ID CODPROV,
	    S.NM_SPR PROVEEDOR,
	    SHP.CREATE_DATE CREADO,
	    SHP.COMPLETE_DATE RECEPCIÓN,
	    SHP.INVOICE_DATE,
	    DECODE (SHP.STATUS,	0,	'Nuevo',	1,	'En Curso',	2,	'Recibido',	4,	'Cancelado',		'Revisar ORSIM'	) ESTATUS,
	    DECODE (SHP.FROM_LOCATION_TYPE, 'SP', 'Proveedor', 'WH', 'Almacen', 'Revisar ORSIM') TIPO_RECEPCION,
      --shp.comment_desc,
	    SHP.EMPLOYEE_ID
FROM RK_SHIPMENTS SHP
	INNER JOIN PA_SPR S ON S.ID_SPR = SHP.FROM_LOCATION_ID
	INNER JOIN (
			SELECT PSR.ID_STR_RT,
				    PO.NM_ORGN
			FROM PA_ORGN PO
				INNER JOIN PA_STR_RTL PSR ON PSR.ID_PRTY = PO.ID_PRTY_ORGN
				AND	PSR.RK_STORE_TYPE = 'C'
		) ST ON ST.ID_STR_RT = SHP.STORE_ID
WHERE SHP.FROM_LOCATION_ID IN (		4, 3, 200000	)  --Comentar para traer todos los Proveedores 
AND	SHP.CREATE_DATE >= '01/07/2016'
ORDER BY
	ST.NM_ORGN,
	SHP.CREATE_DATE,
	SHP.ASN_ID,
	SHP.INVOICE_ID;