SELECT ID.ID_LOG,
	    ID.ID_TBL,
	    ID.PHARMACY_ID,
	    ID.ACT_TYP,
	    TRUNC (ID.TS_REG) AS TS_REG
FROM (
		SELECT ID.*,
			    IL.ID_ITM
		FROM OSB.ITEMS_DETAILS ID
			INNER JOIN ITEMS_LOG IL ON ( ID.ID_LOG = IL.ID_LOG
				AND
					TRUNC (ID.TS_REG) = TRUNC (IL.TS_REG)
				AND
					TRUNC (ID.TS_REG) >= '01/01/17'
			)
		UNION ALL SELECT ID.*,
			    IU.ID_ITM
		FROM OSB.ITEMS_DETAILS ID
			INNER JOIN ITEMS_UPC IU ON ( ID.ID_LOG = IU.ID_LOG
				AND
					TRUNC (ID.TS_REG) = TRUNC (IU.TS_REG)
				AND
					TRUNC (ID.TS_REG) >= '01/01/17'
			)
		UNION ALL SELECT ID.*,
			    IC.ID_ITM
		FROM OSB.ITEMS_DETAILS ID
			INNER JOIN ITEMS_CHANGES_PRICES IC ON ( ID.ID_LOG = IC.ID_LOG
				AND
					TRUNC (ID.TS_REG) = TRUNC (IC.TS_REG)
				AND
					TRUNC (ID.TS_REG) >= '01/01/17'
			)
	) ID
	INNER JOIN CHANGE_LOG CL ON ( ID.ID_LOG = CL.ID_LOG
		AND
			ID.ID_TBL = CL.ID_TBL
		AND
			ID.PHARMACY_ID = CL.ID_FAR
		AND
			ID.ACT_TYP = CL.ACT_TYP
		AND
			TRUNC (ID.TS_REG) = TRUNC (CL.TS_REG)
	)
WHERE CL.IND_SINC = '-3'
GROUP BY
	ID.ID_LOG,
	ID.ID_TBL,
	ID.PHARMACY_ID,
	ID.ACT_TYP,
	TRUNC (ID.TS_REG);